#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("helpers.lib.yml", "prefix_name")

#@overlay/match by=overlay.subset({"spec": {"template": {"metadata": {}}}}), expects="1+"
---
spec:
  template:
    metadata:
      labels:
        #@overlay/match missing_ok=True
        app.kubernetes.io/name: filer
        #@overlay/match missing_ok=True
        app.kubernetes.io/instance: #@ "filer-" + data.values.name

#@overlay/match by=overlay.subset({"spec": {"template": {"spec": {"containers": []}}}}), expects="1+"
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      #@overlay/replace or_add=False, via=prefix_name
      serviceAccountName:
      containers:
        #@overlay/match by=overlay.subset({"env": []}), expects="0+"
        #@overlay/replace or_add=False, via=overlay.apply
        - env:
            #@overlay/match by=overlay.subset({"valueFrom": {"configMapKeyRef": {}}}), expects="0+"
            #@overlay/replace or_add=False, via=overlay.apply
            - valueFrom:
                configMapKeyRef:
                  #@overlay/replace via=prefix_name
                  name:
            #@overlay/match by=overlay.subset({"valueFrom": {"secretKeyRef": {}}}), expects="0+"
            #@overlay/replace or_add=False, via=overlay.apply
            - valueFrom:
                secretKeyRef:
                  #@overlay/replace via=prefix_name
                  name:
      #@overlay/match missing_ok=True
      #@overlay/replace or_add=False, via=overlay.apply
      volumes:
        #@overlay/match by=overlay.subset({"configMap": {}}), expects="0+"
        #@overlay/replace or_add=False, via=overlay.apply
        - configMap:
            #@overlay/replace via=prefix_name
            name:
