version: '3.8'
services:
  db:
    image: 'postgres:16'
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - '${POSTGRES_HOST_PORT}:5432'
volumes:
  dbdata:
