#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: index
  labels:
    app.kubernetes.io/component: index
  annotations:
    kapp.k14s.io/change-rule.migration: upsert after upserting filer.dmaze.github.io/migration
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: index
  replicas: #@ data.values.index.replicas
  template:
    metadata:
      labels:
        app.kubernetes.io/component: index
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9568"
    spec:
      containers:
        - name: index
          image: filer-index
          env:
            - name: POSTGRES_USER
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_DB
            - name: POSTGRES_HOST
            - name: GOSSIP_SECRET
            - name: RELEASE_COOKIE
            - name: SECRET_KEY_BASE
            - name: DATABASE_URL
            - name: POD_IP
            - name: FILER_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: index
  labels:
    app.kubernetes.io/component: index
spec:
  selector:
    app.kubernetes.io/component: index
  clusterIP: None
